SELECT PRODUCTS.NAME,
	PROVIDERS.NAME,
	PRODUCTS.PRICE
FROM PRODUCTS
INNER JOIN PROVIDERS ON PRODUCTS.ID_PROVIDERS = PROVIDERS.ID
INNER JOIN CATEGORIES ON PRODUCTS.ID_CATEGORIES = CATEGORIES.ID
WHERE PRODUCTS.PRICE > 1000
	AND CATEGORIES.NAME = 'Super Luxury';