SELECT NAME,
	CUSTOMERS_NUMBER
FROM LAWYERS
WHERE CUSTOMERS_NUMBER =
		(SELECT MAX(CUSTOMERS_NUMBER)
			FROM LAWYERS)
UNION ALL
SELECT NAME,
	CUSTOMERS_NUMBER
FROM LAWYERS
WHERE CUSTOMERS_NUMBER =
		(SELECT MIN(CUSTOMERS_NUMBER)
			FROM LAWYERS)
UNION ALL
SELECT 'Average' AS NAME,
	ROUND(AVG(CUSTOMERS_NUMBER), 0) AS CUSTOMERS_NUMBER
FROM LAWYERS;