SELECT CANDIDATE.NAME,
	ROUND((((SCORE.MATH * 2) + (SCORE.SPECIFIC * 3) + (SCORE.PROJECT_PLAN * 5)) / 10), 2) AS AVG
FROM CANDIDATE
INNER JOIN SCORE ON CANDIDATE.ID = SCORE.CANDIDATE_ID
ORDER BY AVG DESC;